# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Plugins
plugins:
  - jekyll-paginate

# Setup
title:            "Mossgreen Service Station"
tagline:          'MOT – SERVICING – REPAIRS – TYRES – EXHAUSTS'
# description:      'MOT – SERVICING – REPAIRS – TYRES – EXHAUSTS'
url:              https://mossgreenservicestation.co.uk
baseurl:          /

author:
  name:           'Nick Hood'
  url:            https://cullaloe.net

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/cullaloe/MGSS
